variable "aws_region" {
  description = "The AWS region to create resources in"
  type        = string
  default     = "us-east-1"
}

variable "vpc_cidr_block" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.10.0.0/16"
}

variable "subnet_cidr_a" {
  description = "CIDR block for subnet A"
  type        = string
  default     = "10.10.10.0/24"
}

variable "subnet_cidr_b" {
  description = "CIDR block for subnet B"
  type        = string
  default     = "10.10.20.0/24"
}

variable "availability_zone_a" {
  description = "Availability zone for subnet A"
  type        = string
  default     = "us-east-1a"
}

variable "availability_zone_b" {
  description = "Availability zone for subnet B"
  type        = string
  default     = "us-east-1b"
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t3.micro"
}

variable "home_public_ip" {
  description = "Your home public IP for Customer Gateway"
  type        = string
}

variable "home_subnet_cidr" {
  description = "Your home network CIDR block"
  type        = string
  default     = "10.8.0.0/24"
}

variable "security_group_name" {
  description = "Name of the security group"
  type        = string
  default     = "security-group1"
}

variable "instance1_name" {
  description = "Name tag for EC2 instance 1"
  type        = string
  default     = "Instance1"
}

variable "instance2_name" {
  description = "Name tag for EC2 instance 2"
  type        = string
  default     = "Instance2"
}

variable "vpn_tunnel1_psk" {
  description = "Pre-shared key for VPN tunnel 1 (auto-generated by AWS if not set)"
  type        = string
  sensitive   = true
  default     = null
}

variable "vpn_tunnel2_psk" {
  description = "Pre-shared key for VPN tunnel 2 (auto-generated by AWS if not set)"
  type        = string
  sensitive   = true
  default     = null
}